# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('farm', models.IntegerField()),
                ('album_id', models.CharField(max_length=50)),
                ('nb_pictures', models.IntegerField()),
                ('primary', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=50)),
                ('is_journee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('farm', models.IntegerField()),
                ('secret', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=50)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album')),
            ],
        ),
    ]
